//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace luke_josh_project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokerResult
    {
        public int Id { get; set; }
        public int PokerMatchId { get; set; }
        public int PokerUserId { get; set; }
        public int Placing { get; set; }
    
        public virtual PokerMatch PokerMatch { get; set; }
        public virtual PokerUser PokerUser { get; set; }
    }
}
